---
#terminal scripts :
# 1)to create prod jar :  mvn clean install
# 2) to launch the prod jar and specify a profile to select :  java -jar .\spring-boot-tutorial-1.0.0.jar --spring.profile.active=prod

#server port
server:
  port: '8082'
spring:
  profiles:
    active: dev
...
---
#MySql driver config
spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#custumized configs
welcome:
  message: Welcome to JEE World

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
...
---
#MySql driver config
spring:
  profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp_prod
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
...
---
#custumized configs
welcome:
  message: Welcome to JEE World
...